name: autorun github actions # 배포 자동화
on: [pull_request]
jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x, 17.x]

    runs-on: macOS-latest # 배포 시 체크
    name: "autorun"

    steps:
      # 자동 실행 - 배포시 우분투로, 명령어 확인
      # - name: autorun
      #   run:
      #     yarn -
      #     yarn build  # 명령어 확인

      # 실패시 슬랙 알림
      # - name: Notify failure
      #   uses: 8398a7/action-slack@v3
      #   env:
      #     SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
      #   with:
      #     status: ${{ job.status }}
      #     username: github-actions
      #     channel: "#github"
      #   if: failure()
