name: typecheck github actions
on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [develop, feature/**]
jobs:
  build:
    strategy:
      matrix:
        node-version: [16.x]

    runs-on: ubuntu-latest
    name: 'Type Check'

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: '16'
      # ts type check
      - name: Type Check
        run: |
          yarn install
          tsc --project src/index.ts

      # 실패 시 슬랙에 알림
      - name: Notify failure
        uses: 8398a7/action-slack@v3
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        with:
          status: ${{ job.status }}
          author_name: Github Action Test # default: 8398a7@action-slack
          username: github-actions
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
          channel: '#github'
        if:
          failure()
          #always() # Pick up events even if the job fails or is canceled.v
